name: Build and push Docker image

on:
  push:
    branches:
      - main
    tags:
      - '*'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE: my-docker-username/bakemyday
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}, ${{ env.DOCKER_IMAGE }}:latest
          build-args: |
            MAVEN_OPTS=-Dmaven.repo.local=/workspace/.m2/repository
            JAR_FILE=target/bakemyday-0.0.1-SNAPSHOT.jar
